/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Faculty;

import javax.swing.*;
import java.awt.*;
import model.Faculty;
/**
 *
 * @author 123
 */
public class FacultyDashboard extends javax.swing.JPanel {
    
    private final Faculty me;

    public FacultyDashboard(Faculty me) {
        this.me = me;
        setLayout(new java.awt.BorderLayout());

        String displayName = (me != null) ? this.me.getFirstName() + " " + this.me.getLastName() : "";
        JLabel header = new JLabel("Faculty Dashboard — " + displayName);

        header.setFont(header.getFont().deriveFont(Font.BOLD, 16f));
        header.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));

        JTabbedPane tabs = new JTabbedPane();
        tabs.addTab("My Courses", new JPanel());
        tabs.addTab("Students", new JPanel());
        tabs.addTab("Grading & Ranking", new JPanel());
        tabs.addTab("Reports & Tuition", new JPanel());
        tabs.addTab("My Profile", new JPanel());

        add(header, BorderLayout.NORTH);
        add(tabs, BorderLayout.CENTER);
    }

    /**
     * Creates new form FacultyDashboard
     */
    public FacultyDashboard() {
        this(null);
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
