/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Faculty;

import javax.swing.*;
import java.awt.*;
import model.Faculty;
/**
 *
 * @author 123
 */
public class FacultyDashboard extends javax.swing.JPanel {
    
    private model.Faculty me;

    
    public FacultyDashboard() {
        initComponents();
       
    }
    
    public FacultyDashboard(model.Faculty me) {  
        this();
        this.me = me;
        afterInit();                 
    }
    
    private void afterInit() {
        String name = (me != null) ? me.getFirstName() + " " + me.getLastName() : "";
        lblHeader.setText("Faculty Dashboard — " + name);

        initCoursesTab();
        initStudentsTab();
        initGradingTab();
        initReportsTab();
        initProfileTab();
    }
    
    private void initCoursesTab() {
        
    }
    private void initStudentsTab() { }
    private void initGradingTab()  { }
    private void initReportsTab()  { }
    private void initProfileTab()  { }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        tabCourses = new javax.swing.JPanel();
        tabStudents = new javax.swing.JPanel();
        tabGrading = new javax.swing.JPanel();
        tabReports = new javax.swing.JPanel();
        tabProfile = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        lblHeader.setText("Faculty Dashboard");
        add(lblHeader, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout tabCoursesLayout = new javax.swing.GroupLayout(tabCourses);
        tabCourses.setLayout(tabCoursesLayout);
        tabCoursesLayout.setHorizontalGroup(
            tabCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        tabCoursesLayout.setVerticalGroup(
            tabCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        tabs.addTab("My Courses", tabCourses);

        javax.swing.GroupLayout tabStudentsLayout = new javax.swing.GroupLayout(tabStudents);
        tabStudents.setLayout(tabStudentsLayout);
        tabStudentsLayout.setHorizontalGroup(
            tabStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        tabStudentsLayout.setVerticalGroup(
            tabStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        tabs.addTab("Students", tabStudents);

        javax.swing.GroupLayout tabGradingLayout = new javax.swing.GroupLayout(tabGrading);
        tabGrading.setLayout(tabGradingLayout);
        tabGradingLayout.setHorizontalGroup(
            tabGradingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        tabGradingLayout.setVerticalGroup(
            tabGradingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        tabs.addTab("Grading & Ranking", tabGrading);

        javax.swing.GroupLayout tabReportsLayout = new javax.swing.GroupLayout(tabReports);
        tabReports.setLayout(tabReportsLayout);
        tabReportsLayout.setHorizontalGroup(
            tabReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        tabReportsLayout.setVerticalGroup(
            tabReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        tabs.addTab("Reports & Tuition", tabReports);

        javax.swing.GroupLayout tabProfileLayout = new javax.swing.GroupLayout(tabProfile);
        tabProfile.setLayout(tabProfileLayout);
        tabProfileLayout.setHorizontalGroup(
            tabProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        tabProfileLayout.setVerticalGroup(
            tabProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        tabs.addTab("My Profile", tabProfile);

        add(tabs, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHeader;
    private javax.swing.JPanel tabCourses;
    private javax.swing.JPanel tabGrading;
    private javax.swing.JPanel tabProfile;
    private javax.swing.JPanel tabReports;
    private javax.swing.JPanel tabStudents;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
