/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Admin;

import javax.swing.*;
import java.awt.*;
import accesscontrol.*;
import business.*;
import model.*;
import UI.Admin.AdminDashboard; 
import UI.Student.StudentDashboard;

/**
 *
 * @author USER
 */
public class ProfileWorkAreaMainFrame extends javax.swing.JFrame {
     private AuthenticationService authService;
     private UniversityDirectory universityDirectory;
    

    /**
     * Creates new form ProfileWorkAreaMainFrame
     */
    public ProfileWorkAreaMainFrame() {
        initComponents();
        
        
        
        
        authService = AuthenticationService.getInstance();
        universityDirectory = UniversityDirectory.getInstance();
        
        new business.DataInitializer().initializeData(); 

        if (authService.getUserByUsername("admin") == null) {
            // Admin(String universityId, String firstName, String lastName, String email)
            Admin admin = new Admin("A001", "System", "Admin", "admin@university.edu");

            // User(String username, String password, String role, Person person)
            User adminUser = new User("admin", "****", "Admin", admin);

            authService.registerUser(adminUser);

            System.out.println("✅ Default admin (admin /****) created.");
        }
        
        if (universityDirectory.getStudents().isEmpty()) {
            DataInitializer dataInitializer = new DataInitializer();
            dataInitializer.initializeData();
            System.out.println("✅ System initialized with sample data");
            System.out.println("📚 Login Credentials:");
            System.out.println("   Admin: admin / admin123");
            System.out.println("   Student: student1 / pass1");
            System.out.println("   Faculty: faculty1 / pass1");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        UserNameTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 48)); // NOI18N
        jLabel3.setText("Digital University System ......");
        jPanel2.add(jLabel3, "card2");

        jSplitPane1.setRightComponent(jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LoginButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("User Name");

        UserNameTextField.setText("admin");

        PasswordTextField.setText("****");
        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LoginButtonActionPerformed
        // TODO add your handling code here:
        //      WorkAreaJPanel ura = new WorkAreaJPanel(workareajpanl);
        String username = UserNameTextField.getText().trim();
        String password = PasswordTextField.getText().trim();

        try {
            User user = authService.login(username, password);

            if (user != null) {
                String role = user.getRole();
                JOptionPane.showMessageDialog(this, "Welcome, " + role + "!");

                CardLayout layout = (CardLayout) jPanel2.getLayout();

                switch (role.toLowerCase()) {
                    case "admin":
                        AdminDashboard adminPanel = new AdminDashboard(universityDirectory);
                        jPanel2.add("AdminDashboard", adminPanel);
                        layout.show(jPanel2, "AdminDashboard");
                        break;
                    case "faculty":
                        // TODO: add FacultyDashboard
                        model.Faculty me = (model.Faculty) user.getPerson();
                        UI.Faculty.FacultyDashboard facPanel = new UI.Faculty.FacultyDashboard(me);
                        jPanel2.add("FacultyDashboard", facPanel);
                        layout.show(jPanel2, "FacultyDashboard");
                        break;
                        
                    case "student":
                        // ADDED: Student case
                        StudentDashboard studentPanel = new StudentDashboard(universityDirectory);
                        jPanel2.add("StudentDashboard", studentPanel);
                        layout.show(jPanel2, "StudentDashboard");
                        break;
                    default:
                        JOptionPane.showMessageDialog(this, "Unknown role: " + role);
                        return;
                }

                // ✅ 登入後保留左側登入區，設定分隔比例
                jSplitPane1.setDividerLocation(180);  // 左側寬度
                jSplitPane1.setDividerSize(5);        // 分隔線可見
                jPanel1.setVisible(true);             // 保持登入區顯示

            } else {
                JOptionPane.showMessageDialog(this, "Invalid username or password.");
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Login Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1LoginButtonActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new ProfileWorkAreaMainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
